[package]
name = "sqe-core"
version = "0.0.1-alpha"
edition = "2024"
 
[dependencies]
qrcode = "0.14.1"
keyarray = "0.0.1-alpha"
lazy_static = "1.5.0"
serde_json = "1.0"
clap = { version = "4.2", features = ["derive"] }
 
[build-dependencies]
chrono = "0.4"
